### ISSUE TITLE
Use `api-interfaces` in the StabilityAI organization instead of the `stability-sdk`

### ISSUE THREAD

**Issue by cruhl** [jakiestfu/stability-ts#11]
Hello!

I plan on writing more about this, but TL;DR: using the `api-interfaces` [project](https://github.com/Stability-AI/api-interfaces) instead of the `stability-sdk` would be ideal.

Also, I'd love to chat if you're up for it!

I work at Stability.

**Comment by johnsabath** [comment]
I dig a bit of digging to see how `stability-sdk` was being pulled in, and it looks like it's using the new `api-interfaces` project after all 🎉 

https://github.com/jakiestfu/stability-ts/blob/main/package.json#L46

**Comment by cruhl** [comment]
Oh sick, should I close this?

**Comment by derwo** [comment]
Yeah this was updated with v1.3.0
See #10
