### ISSUE TITLE
Unexpected token ? crash

### ISSUE THREAD

**Issue by web-gan** [jakiestfu/stability-ts#3]
Hi! Recently installed this through NPM and am trying to run it on a backend server. The app is currently crashing with the following error:

`SyntaxError: Unexpected token '?'` where you're setting `const requestId = draft.requestId ?? uuid4()`

Let me know if you have any ideas! Thanks!

**Comment by jakiestfu** [comment]
What version of node are you using?

**Comment by jakiestfu** [comment]
[Added some babel transpilation](https://github.com/jakiestfu/stability-ts/pull/5/files), this should be fixed in version `1.2.0`

**Comment by jakiestfu** [comment]
@web-gan Did this fix your issues?

**Comment by web-gan** [comment]
Hey there - thanks for circling back. This did fix the issue, thanks! Just running into another where it doesn't seem to actually be making the call to DreamStudio (no credits are dropping from my account). I wonder if this has to do with me using this in a JS file and not Typescript?

**Comment by jakiestfu** [comment]
@web-gan Well I'm using webpack and babel now to convert to JS so it shouldn't be an issue. Can you console log the arguments for me of the `end` function and share them here? There could be an error message in there.

```
api.on('end', (data) => {
  console.log('Generating Complete', data)
})
```

**Comment by web-gan** [comment]
This was a typo on my end! Was using `token` instead of `apiKey`. Thanks for the help! All is working now!

**Comment by jakiestfu** [comment]
That was actually my fault! It was a typo in the readme 😭 It's since been fixed. Thanks!
