### ISSUE TITLE
Async/await and NoStore questions

### ISSUE THREAD

**Issue by Abel1011** [jakiestfu/stability-ts#7]
Hi, thanks for the library, I was testing it and was able to create some images on my computer.

On that note, I wanted to ask a few questions.

Is it possible to use the api with async/await, is it possible for you to include an example?

I am trying to save the image to an external provider and using the noStore option set to true. However, even though the image is not saved, an output folder is still created. Is there any way to avoid creating the folder?

Regards

**Comment by jakiestfu** [comment]
I will be pushing a fix upstream to address this. Only issue is you can generate multiple images per invocation, but using a single await means if you’re generating multiple images, you won’t get the response until all are done.

Does this meet your requirements, @Abel1011 ?

**Comment by jakiestfu** [comment]
This is fixed in `v1.3.0`!
